# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d848aad55251e30c85c693529c208ee7a564209bdac88f13bd0cff3f2c7eb034e11877e366efdd2c63ad3ddc2232be752d786cc5e582c6ceefa1d322287368c

test:
  secret_key_base: 2f7a90fa1f253418200d34b90083c381f78ba6d3efcf6d0f76a4059d955b59e09dfd58a3d50b4aedfa5043f1969f728e77f6aae7a5dfb0d68c824a7649c6e34e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
